### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by LinkyModz** [Ryan-M-Smith/Quinton-VoiceAssistant#8]
Hey man we should code something together im still learning but ill manage it you probably don't remember me but i use to use scratch my name on there was jsandoval7.

**Comment by Ryan-M-Smith** [comment]
@LinkyModz Sounds like fun!

**Comment by LinkyModz** [comment]
> @LinkyModz Sounds like fun!

do you use instagram or discord?

**Comment by Ryan-M-Smith** [comment]
No

**Comment by LinkyModz** [comment]
> No

hmm what do you use?
